### ISSUE TITLE
Enable export of MSSQL metrics 

### ISSUE THREAD

**Issue by Seth1u** [fantom732315/Grafana#1]
Hello how to enable export of MSSQL metrics for your dashboard?

**Comment by theogbubbie** [comment]
Just define it to the enabled collectors like this:

msiexec /i <PATH_TO_FILE>\windows_exporter-0.16.0-amd64.msi ENABLED_COLLECTORS=[defaults],mssql

**Comment by fantom732315** [comment]
1. Install Windows_exporter 0.16
2. Add new target to prometheus
3. Add dashboard

**Comment by Seth1u** [comment]
Thank you it's work without PKI metrics
